name: Farnborough Fireside Gatherings
favicon: null
layout_spectrum: 0.50422
typography_spectrum: 0.36161
title: Hearthstone Fireside Gatherings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#79ace3'
    - '#e9e5e6'
    - '#050704'
    - '#0396aa'
    - '#8f8142'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
