name: Farnborough Fireside Gatherings
favicon: null
layout_spectrum: 0.48768
typography_spectrum: 0.20116
title: Hearthstone Fireside Gatherings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000105'
    - '#423320'
    - '#92652a'
    - '#e5a01e'
    - '#fecf25'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
