name: Farnborough Fireside Gatherings
favicon: null
layout_spectrum: 0.48768
typography_spectrum: 0.20116
title: Hearthstone Fireside Gatherings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060808'
    - '#6e00d1'
    - '#35c9dd'
    - '#005bcc'
    - '#a560c7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
