name: Farnborough Fireside Gatherings
favicon: null
layout_spectrum: 0.97888
typography_spectrum: 0.10686
title: Hearthstone Fireside Gatherings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040309'
    - '#4f3840'
    - '#6d6f24'
    - '#e7c24d'
    - '#a5290b'
  brandStrength: 0.9504134859889746
  lightness: 0.9737528276164085
  saturation: 0.7868932851124555
  rhythmicContrast: 0.7231876463629305
purpose: []
